### ISSUE TITLE
PDFKit unable to render document with GIF

### ISSUE THREAD

**Issue by JakeTrock** [alafr/SVG-to-PDFKit#112]
I am trying to use a pdf document with an embedded gif-typed base64 image. For some odd reason, when I used the png version of the system, the png worked without issue, but when I try to use a gif with the same exact system, it refuses to render, despite it creating a functional svg in the prior function.
Here is what it spits back when I try to use a GIF embed image:
`<image x="11436" y="6720" width="4339" height="4339" preserveAspectRatio="none" xlink:href="data:image/gif;base64,R0lGODdhUgBSAIAAAAAAAP///ywAAAAAUgBSAAAC/4yPqcvtD6OctNqLs968+w+G4kiW5mkC6sqyRgu88aLKsGzDLaXreR0AKoA9XLC3mwhps1vDdcwNZ4wlxJogJqsrIxSBBVMjWqhWGj2GD9+0c839Nefo8ni6tJ+Vc3OfzoYkZuSVBMckV7gn17boZnj3oAfo4IdW+ed4lUn51PV4qPgZmhU5mMb4WSimWcpjGkio5hOLOis79Yo0Crjn28tZxLf7u/poPClMkte5e4qyecqsbAvSuOU6a4mYTb05rdpNu4aVDMvVKkwe/CeKsc0KGafN+0uKWdcsWAteXM2XT5YzfmPeALPgJ2E7UOdu/Yuni1M+ew3hMbkXaJu/Nv94Dh7bYBDZQnQeWyGUOAzYIUccyaCUoDFcLlstYUIK6Ynis4cXDOIk6a4Wrp4epRWld22nUklHRQrc93SezZ0tzQ0NihGfUIdGf4ozSTQRzU5db5qtyVQss6sMFbqVmfYir1Rrx1JDq7UjRSfG6BaEG40eRIKX5JZlq5Uv1494F9tB7DImOEz+qAKOPNfx5YD/Jqesa1FyRXk8KYd7bFfl6JgafG4updNT4ZNvbcae1/jV4MpIT/ue2frvRuG0Cpdr2JHzTHWwiL3+tnBdKrbOs4IkvZyYXmzWsH+FmrE45oGiFLPMXDci+bbYzvO2DtkqQ9PHlwbGPW6k3Ppbpwpn/jgYUOxdY90kfYVnWnntPffdecnNB5tZ9sn2X3oIQhiPQhPiZ5FtqrnHIIeZRaTgU7lRKKJRGZLmTVgUJpUaTi3Spl1v0/HE24b77cOcVyriiBw0Qg5JZJFGHolkkkouyWSTTiJZAAA7"/>`
(keep in mind that this is within another svg document, which is too long to post here)
![Screenshot_20200217_111128](https://user-images.githubusercontent.com/17764452/74670112-83f3b880-5176-11ea-99e0-d3ef609dfdc7.png)

Does anyone know how this problem could be resolved?

**Comment by alafr** [comment]
GIF is not supported. This is just an "add-on" for PDFKit which itself can't read GIF images.
> Image embedding
> Supports JPEG and PNG files (including indexed PNGs, and PNGs with transparency)

**Comment by JakeTrock** [comment]
I guess I'll go to them instead.
