### ISSUE TITLE
Scaled line with a mask is not rendered properly

### ISSUE THREAD

**Issue by iherasymenko** [alafr/SVG-to-PDFKit#116]
Here's the reproducer. Comment out `mask="url(#mask_1)"` to see the difference.

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="600" version="1.1" viewBox="0 0 600 600" width="600">
    <defs>
        <mask id="mask_1">
            <g>
                <rect fill="white" height="600" width="600"/>
                <rect fill="black" id="rect_1" height="10" width="100" x="216" y="180"/>
            </g>
        </mask>
        <g id="line_1" transform="matrix(9.72272 9.72272 -9.72272 9.72272 320 186.73165)">
            <line stroke-width="3" x1="-8" x2="8" y1="8" y2="-8"/>
        </g>
    </defs>
    <use stroke="red" mask="url(#mask_1)" xlink:href="#line_1"/>
</svg>
```

**Comment by iherasymenko** [comment]
I am also willing to contribute. If you could point out where to look at, I would be happy to investigate further and create a PR.

Thanks for the amazing lib!

**Comment by iherasymenko** [comment]
@alafr I did some research in this area and it turns out that the fix could be a very simple change, but I'm not sure this is the correct way. So, here is my story.

The root cause of the problem is that the bounding box passed to the `useMask` function https://github.com/alafr/SVG-to-PDFKit/blob/15ab82dff389bb990dd4e9493ce8531cf9eb6298/source.js#L2044

does not account for the `stroke` and `stroke-width` attributes of the masking shape. As a result, the `height` and `y` parameters are computed incorrectly, while `x` and `width` are fine. 
https://github.com/alafr/SVG-to-PDFKit/blob/15ab82dff389bb990dd4e9493ce8531cf9eb6298/source.js#L2054-L2057

Clipping a newly created group to a wrong rectangle results in this issue. The obvious solution would be to modify the `getBoundingBox` function so that it properly handles the stroke attributes.

However, I found another solution which is much easier to implement. 

Removing the following line solves the problem. 
https://github.com/alafr/SVG-to-PDFKit/blob/15ab82dff389bb990dd4e9493ce8531cf9eb6298/source.js#L2059

From my very-very limited perspective, I clipping a newly created group which contains zero objects does not make sense.

I still assume clipping is done **intentionally**. Unfortunately git commit history does not tell much of a story on why this line is required so I hope you can shed some light on this mystery :-)

I ran the test suite with the aforementioned change applied, and didn't notice any regression caused by it.

`masking-*` tests are passing with 0% difference and so is the rest of the test suite.

cc: @cabrilo

**Comment by alafr** [comment]
Indeed, I don't think that line is useful. Let's just remove it.

**Comment by iherasymenko** [comment]
Thank you @alafr . May we expected a new version which contain this fix to be released in the near feature?
