### ISSUE TITLE
Clip-path and tranform issue

### ISSUE THREAD

**Issue by Greeeeyyyss** [alafr/SVG-to-PDFKit#120]
Hi! I have an SVG that does not render correctly when generating to pdf. I found out the clip-path element is causing the issue. Other SVGs I tried with clip path are fine. 

`<svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 493.12 612">
  <defs>
    <style>
      .cls-1{fill:none;}.cls-2{fill:#fff;}.cls-3{fill:#ffffe9;}.cls-4{clip-path:url(#clip-path);}.cls-5{fill:#b3ddff;}.cls-6{clip-path:url(#clip-path-2);}.cls-7{fill:url(#New_Gradient_Swatch_1);}.cls-8{fill:url(#linear-gradient);}.cls-9{fill:#f4e2bd;}
    </style>
    <clipPath id="clip-path" transform="translate(-385.77)">
      <rect class="cls-1" x="451.48" width="395.85" height="612"/>
    </clipPath>
    <clipPath id="clip-path-2" transform="translate(-385.77 0)">
      <path class="cls-1"
            d="M812.52,374.82c10-6.15,17.44-15.25,19.23-28.81,2.17-16.39-5.68-32.64-16.21-45.38s-23.77-22.95-35.18-34.91c-13-13.57-23.46-29.28-36.16-43.07s-28.37-26-46.79-29.45c-18.65-3.53-38,2.31-54.5,11.73s-30.67,22.27-45.42,34.2a509.12,509.12,0,0,1-74.89,50.3c-11.18,6.14-22.71,11.94-32.35,20.3s-17.38,19.77-18.3,32.5c-.66,9.18,2.29,18.38,7.12,26.22,12.7,20.6,37.27,31.39,61.34,33.9s48.24-2,72.19-5.46a844.07,844.07,0,0,1,115.94-8.64c12.15-.06,24.33.14,36.45-.85C780.4,386.13,798.85,383.23,812.52,374.82Z"/>
    </clipPath>
    <linearGradient id="New_Gradient_Swatch_1" x1="208.75" y1="302.4" x2="403.01" y2="486.98"
                    gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="0" stop-color="#ffda00"/>
      <stop offset="1" stop-color="#ff7500"/>
    </linearGradient>
    <linearGradient id="linear-gradient" x1="62.17" y1="373.03" x2="480.61" y2="373.03" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#0068ff"/>
      <stop offset="1" stop-color="#7ab0ff"/>
    </linearGradient>
  </defs>
  <rect id="Background_Color" data-name="Background Color" class="cls-3" x="65.71" width="395.85" height="612"/>
  <g id="Background">
    <g class="cls-4">
      <g id="Clouds">
        <path class="cls-5"
              d="M860.35,185.58c-6.16-11.75-21.39-15.7-28.46-3.92-5.44-23.79-40.45-17.33-43.85-5.61S750.82,198,750.82,198h128C879.48,185.85,866.91,178.78,860.35,185.58Z"
              transform="translate(-385.77)"/>
        <path class="cls-5"
              d="M495.31,231.92c-6.16-11.75-21.4-15.7-28.46-3.92-5.44-23.79-40.45-17.34-43.85-5.61s-37.23,21.93-37.23,21.93H513.83C514.44,232.19,501.86,225.12,495.31,231.92Z"
              transform="translate(-385.77)"/>
      </g>
    </g>
    <g id="sea">
      <path class="cls-2"
            d="M812.52,374.82c10-6.15,17.44-15.25,19.23-28.81,2.17-16.39-5.68-32.64-16.21-45.38s-23.77-22.95-35.18-34.91c-13-13.57-23.46-29.28-36.16-43.07s-28.37-26-46.79-29.45c-18.65-3.53-38,2.31-54.5,11.73s-30.67,22.27-45.42,34.2a509.12,509.12,0,0,1-74.89,50.3c-11.18,6.14-22.71,11.94-32.35,20.3s-17.38,19.77-18.3,32.5c-.66,9.18,2.29,18.38,7.12,26.22,12.7,20.6,37.27,31.39,61.34,33.9s48.24-2,72.19-5.46a844.07,844.07,0,0,1,115.94-8.64c12.15-.06,24.33.14,36.45-.85C780.4,386.13,798.85,383.23,812.52,374.82Z"
            transform="translate(-385.77)"/>
      <g class="cls-6">
        <rect class="cls-5" x="62.17" y="162.93" width="418.44" height="196.89"/>
        <circle class="cls-7" cx="280.74" cy="370.81" r="50.99"/>
        <polygon class="cls-8" points="476.88 386.25 62.17 367.88 62.17 359.81 480.61 359.81 476.88 386.25"/>
        <path class="cls-9" d="M866.39,460.89H448V365.94l418,20.48a.4.4,0,0,1,.4.4Z" transform="translate(-385.77)"/>
        <path class="cls-2"
              d="M568,298.93c-6.16-11.76-21.4-15.71-28.46-3.93-5.44-23.79-40.45-17.33-43.85-5.6s-37.23,21.92-37.23,21.92H586.54C587.15,299.19,574.57,292.13,568,298.93Z"
              transform="translate(-385.77)"/>
        <path class="cls-2"
              d="M626,257.52h72.08c.66-13.1-14.08-20.31-20-10.48-3.5-15.29-26-11.14-28.18-3.61S626,257.52,626,257.52Z"
              transform="translate(-385.77)"/>
        <path class="cls-2"
              d="M779.37,317.84h72.08c.66-13.11-14.09-20.32-20-10.49-3.5-15.29-26-11.14-28.18-3.6S779.37,317.84,779.37,317.84Z"
              transform="translate(-385.77)"/>
        <path class="cls-2"
              d="M439.28,212.29h72.08c.66-13.11-14.09-20.31-20-10.48-3.5-15.29-26-11.14-28.18-3.61S439.28,212.29,439.28,212.29Z"
              transform="translate(-385.77)"/>
      </g>
    </g>
  </g>
</svg>
`

Here's the what the SVG looks like originally and how it is rendered.

<img width="1122" alt="Screen Shot 2020-06-15 at 3 18 39 PM" src="https://user-images.githubusercontent.com/10753499/84628563-78917d80-af1b-11ea-90fc-5b0db582bdbe.png">

**Comment by alafr** [comment]
Thanks for the report. The transform attribute was not used at all, it should be fixed now.
