### ISSUE TITLE
Using CMYK colors

### ISSUE THREAD

**Issue by Wewill** [alafr/SVG-to-PDFKit#129]
Hey team, 

Thank you for your excellent work here. I'm using PDFMake, a javascript library using PDFKit and SVG-to-PDFKit.

When importing a svg to pdfmake, about CMYK in SVG, I tried :

`...<style>.a{fill:device-cmyk(1.00, 0.90, 0.25, 0.00) #654e9a;"}</style></defs><title>logo</title><path class="a" d=....`
Not working

`...<style>.a{fill:#654e9a device-cmyk(1.00, 0.90, 0.25, 0.00) ;"}</style></defs><title>logo</title><path class="a" d=...`
Not working

`...</defs><title>logo</title><path fill="#654e9a device-cmyk(1.00, 0.90, 0.25, 0.00)" class="a" d=...`
Not working

pdfmake call to a svg :
`... { svg: ccppm_global.logo_fifam, width: dimension, fill:'#FF0000', color:[100,90,25,0], fillColor:[100,90,25,0], },`
Not working 

Do you have an idea to work with CMYK colors ? A callback ? 

Best regards, 
Wilhem

**Comment by andrewzolotukhin** [comment]
I would love to have a CMYK support as well.

**Comment by Wewill** [comment]
Anything ?

**Comment by Wewill** [comment]
Is this functionnality is working ? https://github.com/alafr/SVG-to-PDFKit/pull/63

**Comment by naeem-brikl** [comment]
Please, have a look at this #130

**Comment by Wewill** [comment]
> Please, have a look at this #130

Thank for your reply @naeem-brikl 
I just tried your <svg> :

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 360">
  <title>CMYK BOXES</title>
  <style>
    .red_cmyk {fill:cmyk(0, 85, 65, 0)}
    .blue_cmyk {fill:cmyk(90, 55, 0, 0)}
  </style>
  <rect x="10" y="10" width="460" height="340" fill="none" stroke="grey"/>
  <text x="40" y="40" font-size="30" fill="cmyk(0, 85, 65, 0)">THESE SHOULD BE RED:</text>
  <rect x="40" y="50" width="120" height="120" fill="cmyk(0, 85, 65, 0)"/>
  <rect x="180" y="50" width="120" height="120" style="fill:cmyk(0, 85, 65, 0)"/>
  <rect x="320" y="50" width="120" height="120" class="red_cmyk"/>
  <text x="40" y="210" font-size="30" fill="cmyk(90, 55, 0, 0)">THESE SHOULD BE BLUE:</text>
  <rect x="40" y="220" width="120" height="120" fill="cmyk(90, 55, 0, 0)"/>
  <rect x="180" y="220" width="120" height="120" style="fill:cmyk(90, 55, 0, 0)"/>
  <rect x="320" y="220" width="120" height="120" class="blue_cmyk"/>
</svg>`

But, it's not working with PDFMake as you can see :

![Capture d’écran 2020-11-18 à 09 07 58](https://user-images.githubusercontent.com/3178443/99502844-edab2800-297d-11eb-8606-52ac2bd2ebbe.png)


I already opened a ticket in PDFMake, so I guess the issue comes from PDFMake ? 
https://github.com/bpampuch/pdfmake/issues/2101

Best

**Comment by naeem-brikl** [comment]
I guess we'll have to wait for both libraries to update

**Comment by Wewill** [comment]
@naeem-brikl ok thank you, I will wait !
