### ISSUE TITLE
Doesn't work properly when webpack has minimization enabled

### ISSUE THREAD

**Issue by grumd** [alafr/SVG-to-PDFKit#137]
I have svg-to-pdfkit working completely fine in web when building with webpack, but as soon as I just flip "optimization.minimize: false" to "optimization.minimize: true" in webpack, fill with `<pattern>` stops working and all I see is solid black fill.

Using latest version for PDFKit and this plugin, and webpack 5.

It's a long shot posting here but I'm just feeling lucky, maybe anyone has an idea what can cause black fill instead of pattern fill... Really hard to debug webpack's minimizer. I tried putting all the pdf-related modules into "excludes" for TerserPlugin but it didn't help.

**Comment by grumd** [comment]
I didn't really understand how exactly terser breaks svg-to-pdfkit, but I was able to create a separate chunk for this package, and then disable TerserPlugin only for that chunk 
![image](https://user-images.githubusercontent.com/5869818/106290925-b2698700-6253-11eb-9434-bd50257d60d2.png)

**Comment by pjrocks70** [comment]
To fix this issue I have used fnames: true in terseroptions.

	new TerserPlugin({
						extractComments: false,
						terserOptions: {
							keep_classnames: true,
							keep_fnames: true,
							},
					})
