### ISSUE TITLE
Positioning of elements not correct

### ISSUE THREAD

**Issue by Sempervivum** [alafr/SVG-to-PDFKit#15]
Great script, exactly what I needed. However I encountered two issues:
1. Number.isNaN() caused an error in IE11. I could fix this simply by removing "Number.".
2. The position of elements is not always correct. I used the script for a Highcharts graph. The txt file is the SVG code originally exported from the graph and shows it as it should be when the extension is changed to "svg". If compared to the PDF the position of the elements on the axes is not exactly correct. The left dots of the graph cover the "%" characters on the y axis.
Would be great if this could be fixed.
[mychart-svgtopdfkit.pdf](https://github.com/alafr/SVG-to-PDFKit/files/588134/mychart-svgtopdfkit.pdf)
[mychart-svgtopdfkit.txt](https://github.com/alafr/SVG-to-PDFKit/files/588136/mychart-svgtopdfkit.txt)

**Comment by alafr** [comment]
Thanks for the report!
Apparently changing `Number.isNaN` causes the wrong positioning.
I made a fix to the script, can you confirm if it works now and reopen the issue if not?

**Comment by Sempervivum** [comment]
Works perfectly now, thanks for the very quick support!
