### ISSUE TITLE
Add support for links (<a> elements)

### ISSUE THREAD

**Issue by alafr** [alafr/SVG-to-PDFKit#18]
I think it won't be possible because in PDFKit (and in PDF 1.3) links are only supported for a few basic shapes. And even with the polygon links supported it would be difficult to implement.
I keep this issue open because the children of the &lt;a> tag must be rendered even without the link.

**Comment by alafr** [comment]
Children of `<a>` elements are rendered since commit [84064ba](https://github.com/alafr/SVG-to-PDFKit/commit/84064ba)

**Comment by peonmodel** [comment]
could <a> be honored if the children are just text elements? i am just trying to make some simple text into a link

**Comment by alafr** [comment]
Yes it can probably be done. I see a few options:
1. Add link support for basic rectangular texts (difficulty: how to determine if a text is rectangular)
2. Add complete link support for text, with a link for each character (problem: PDFKit has no support for rotated links and text can be rotated by many different ways)
3. Add the link to the whole bounding box of the element (problem: the link will also be active outside of the non-rectangular elements)
I think the option 3 is reasonably easy to implement but since in can have undesired results it should be offered as an option. I don't have time to try this right now but if you want you can send a pull request.

**Comment by peonmodel** [comment]
a related bug

commit 84064ba seems to only work for top level `<a>`
`<a>` that are children of text elements are completely ignored, `<a>` children are ignored

**Comment by alafr** [comment]
It would be good to do it like chrome, I had never noticed that it makes oversized links when printing as PDF. It's actually quite rare to have non-rectangular links.
I almost fixed the related bug, there is still an issue when a `<textPath>` is a direct child of the `<a>` element.

**Comment by alafr** [comment]
I implemented support for links in the beta branch of the this repository

**Comment by alafr** [comment]
Support for links added in version 0.1.6
