### ISSUE TITLE
Multi point paths (style attribute)

### ISSUE THREAD

**Issue by Alex-Code** [alafr/SVG-to-PDFKit#22]
A multipoint path with a stroke width of 1px that represents a line gets drawn as a solid shape.

```xml
<svg width="700" height="200">
  <path style="opacity: 1; fill: none; stroke: rgb(0, 0, 0); stroke-width: 1px;" d="M7,12.083L166,105.42093175853017L324,125.16338582677166L483,128.7788713910761L642,133.91666666666666"></path>
</svg>
```
Expected
![image](https://cloud.githubusercontent.com/assets/1797626/23120480/670be0aa-f754-11e6-9d57-41033c1bad79.png)
Generated
![image](https://cloud.githubusercontent.com/assets/1797626/23120420/2bf0e95c-f754-11e6-8517-697b43200d5d.png)

**Comment by alafr** [comment]
This is because there is no support for the `style` attribute. As a workaround, if the SVG is inserted inside the html document, you can use the `{useCSS: true}` option. If not, you can insert it with javascript inside a hidden `div`.

**Comment by Alex-Code** [comment]
Ah, I've done a quick workaround that sets the styles as attributes before passing the SVG element to the `SVGtoPDF` function.
```javascript
$('path', svg).each(function() {
    var $this = $(this),
        stroke = $this.css('stroke');
    $this.attr('stroke', stroke == 'none' ? 'black' : stroke).attr('stroke-width', 1).attr('fill', 'none');    
});
```

Generates nice coloured lines now.
