### ISSUE TITLE
Draw svg with specific bounds

### ISSUE THREAD

**Issue by awerlang** [alafr/SVG-to-PDFKit#24]
Hey! I have a few SVG's I want to draw side by side, so each one would occupy 1/3 of page's width. The original bounds of each graphic is larger than that, so it happens that they overlap each other.

```
const options = {
    width: doc.page.width / 3,
    height: 150,
};
SVGtoPDF(doc, svg[i], left, 0, options);
```

Is this supported? I need it to resize while keeping aspect ratio.

Thanks in advance!

**Comment by alafr** [comment]
Currently the only solution to achieve this is to put the following attributes to the `svg` node:

- `overflow="hidden"`  (it's by default hidden if you don't have this attribute)
- `viewBox` specified: it is 4 numbers separated by spaces (min_x min_y width height) that specify the bounds of the svg content
- `width="100%"` (this means 100% of `doc.page.width / 3`, you can also use `width="33.333%"` and omit the options).
- `height="100%"` (or `height="150"` and omit the options)
- `preserveAspectRatio` has many possible values depending on the desired alignment (for top/left alignement it's `"xMinYMin meet"`)

**Comment by awerlang** [comment]
`width="100%"` and removing the `height` attribute worked. Thanks for the fast response!
