### ISSUE TITLE
stroke-dasharray doesn't work on circle

### ISSUE THREAD

**Issue by awerlang** [alafr/SVG-to-PDFKit#25]
Take this piece of SVG:

```svg
<circle cx="150" cy="120" fill="transparent" r="57.297469361769855164730224415088"
    stroke="#5776D3" stroke-width="20"
    stroke-dasharray="124.35562805872758 235.64437194127245" stroke-dashoffset="90"></circle>
```

It renders like an arc on browsers, but on PDF it is rendered as a full circle. I see support for `stroke-dasharray` on source code, but I can't figure out why it doesn't work. 

Any ideas?

**Comment by alafr** [comment]
Support for dash-array was added in PDFKit [recently](https://github.com/devongovett/pdfkit/pull/551). It should work if you update PDFKit. It renders about 1/3 of a circle in the [online demo](https://alafr.github.io/SVG-to-PDFKit/examples/demo.htm)

**Comment by awerlang** [comment]
You're right! Thanks for the fast response, again!

**Comment by wptechnology** [comment]
Still the same, stroke-dasharray isn't working on circles ... :/ Do you plan to fix it ?
