### ISSUE TITLE
How to place text after SVG

### ISSUE THREAD

**Issue by thorst** [alafr/SVG-to-PDFKit#26]
Im trying to add an svg, of dynamic height, and then below that place some text. Is there an easy way to know where to set my doc.y?

**Comment by alafr** [comment]
It's not possible right now.
I would like to add this functionality but I'm not sure how it should work. I think the SVGtoPDF() function should return an object with various properties: width, height, endX, endY...
Do the svg have width and height attributes? Can you send one of them?

**Comment by thorst** [comment]
Basically I took the height of the container div and set my doc.y to doc.y
+ hieght. So far it seems ok.

**Comment by thorst** [comment]
Nope, after additional testing my height did not work.

**Comment by alafr** [comment]
The height should be `svg.offsetHeight * 72/96` for most svgs but if you use different units or percentages it probably won't work. Can you attach a sample of the file that is causing trouble?

**Comment by thorst** [comment]
Ok, so Im generating a diagram using mermaid.js. It outputs <svg> and that is what I'm using to import using this library. Your is the only library I found that could handle the output. So THANKS! So I'm not sure why the height of the div I was using wasn't working. I'm guessing because I was trying to have it to the left of the screen to hide it while still allowing it to be its original height. In any case, looking at the svg they had a height attribute. I grabbed that and so far that appears to allow better positioning.

Here is the sample (you can tell its generated):
`<svg id="mermaidId0" width="583" xmlns="http://www.w3.org/2000/svg" height="146" viewBox="0 0 603 166"><style type="text/css" title="mermaid-svg-internal-css">/*  */
#mermaidId0 .node&gt;rect { ; }
#mermaidId0 .node text  { fill:#000; stroke:none; font-weight:300; font-family:"Helvetica Neue",Helvetica,Arial,sans-serf; font-size:14px; }
#mermaidId0 .edgeLabel text  { fill:#000; stroke:none; font-weight:300; font-family:"Helvetica Neue",Helvetica,Arial,sans-serf; font-size:14px; }
#mermaidId0 .cluster rect  { rx:4px; fill: rgb(255, 255, 222); rx: 4px; stroke: rgb(170, 170, 51); stroke-width: 1px; }
*, ::before, ::after { box-sizing: border-box;}
.label { display: inline; padding: 0.2em 0.6em 0.3em; font-size: 75%; font-weight: bold; line-height: 1; color: rgb(255, 255, 255); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.25em;}
.node rect, .node circle, .node ellipse, .node polygon { fill: rgb(236, 236, 255); stroke: rgb(204, 204, 255); stroke-width: 1px;}
.edgePath .path { stroke: rgb(51, 51, 51);}
.edgeLabel { background-color: rgb(232, 232, 232);}
.cluster rect { fill: rgb(255, 255, 222) !important; rx: 4 !important; stroke: rgb(170, 170, 51) !important; stroke-width: 1px !important;}
.cluster text { fill: rgb(51, 51, 51);}
.node text { font-family: "trebuchet ms", verdana, arial; font-size: 14px;}
/*  */
</style><g><g class="output"><g class="clusters"><g class="cluster" id="subGraph0" style="opacity: 1;" transform="translate(387,73)"><rect width="352" height="106" x="-176" y="-53"></rect><g class="label"><g transform="translate(0,0)"><text></text></g></g><text x="0" y="-39" fill="black" stroke="none" id="mermaidId0Text" style="text-anchor: middle;"> Cloverleaf</text></g></g><g class="edgePaths"><g class="edgePath" style="opacity: 1;"><path class="path" d="M342,73L367,73L392,73" marker-end="url(#arrowhead29)" style="stroke: #333; stroke-width: 1.5px;fill:none"></path><defs><marker id="arrowhead29" viewBox="0 0 10 10" refX="9" refY="5" markerUnits="strokeWidth" markerWidth="8" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" class="arrowheadPath" style="stroke-width: 1; stroke-dasharray: 1, 0;"></path></marker></defs></g><g class="edgePath" style="opacity: 1;"><path class="path" d="M161,73L186,73L211,73L236,73" marker-end="url(#arrowhead30)" style="stroke: #333; stroke-width: 1.5px;fill:none"></path><defs><marker id="arrowhead30" viewBox="0 0 10 10" refX="9" refY="5" markerUnits="strokeWidth" markerWidth="8" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" class="arrowheadPath" style="stroke-width: 1; stroke-dasharray: 1, 0;"></path></marker></defs></g></g><g class="edgeLabels"><g class="edgeLabel" style="opacity: 1;" transform=""><g transform="translate(0,0)" class="label"><rect rx="0" ry="0" width="0" height="0" style="fill:#e8e8e8;"></rect><text><tspan xml:space="preserve" dy="1em" x="1"></tspan></text></g></g><g class="edgeLabel" style="opacity: 1;" transform=""><g transform="translate(0,0)" class="label"><rect rx="0" ry="0" width="0" height="0" style="fill:#e8e8e8;"></rect><text><tspan xml:space="preserve" dy="1em" x="1"></tspan></text></g></g></g><g class="nodes"><g class="node" style="opacity: 1;" id="mainthread" transform="translate(289,73)"><rect rx="0" ry="0" x="-53" y="-18" width="106" height="36" style="fill:#cde498;stroke:#13540c;"></rect><g class="label" transform="translate(0,0)"><g transform="translate(-43,-8)"><text><tspan xml:space="preserve" dy="1em" x="1">270_FR_EPIC</tspan></text></g></g></g><g class="node" style="opacity: 1;" id="270_TO_PASSPORT" transform="translate(465,73)"><rect rx="0" ry="0" x="-73" y="-18" width="146" height="36"></rect><g class="label" transform="translate(0,0)"><g transform="translate(-63,-8)"><text><tspan xml:space="preserve" dy="1em" x="1">270_TO_PASSPORT</tspan></text></g></g></g><g class="node" style="opacity: 1;" id="protocol" transform="translate(90.5,73)"><rect rx="0" ry="0" x="-70.5" y="-25" width="141" height="50"></rect><g class="label" transform="translate(0,0)"><g transform="translate(-60.5,-15)"><text><tspan xml:space="preserve" dy="1em" x="1">Type:TcpIp/server</tspan><tspan xml:space="preserve" dy="1em" x="1">Connection:17981</tspan></text></g></g></g></g></g></g></svg>`

**Comment by alafr** [comment]
The height it will take on the PDF is precisely `parseFloat(svg.getAttribute('height')) * 72/96` (SVG pixels to PDF points conversion). Browsers sometimes return estimated values for the dimensions until the element is fully rendered.
I will add the possibility to get the height & width directly with SVG-to-PDFKit because is can be useful when the SVG is not embedded in the page.

**Comment by thorst** [comment]
YES! `doc.y = doc.y + (parseFloat($("#mermaidId0").attr("height")) * 72 / 96)` will provide a more concise height. I started pulling that height but it of course was adding an extra cushion so I appreciate your follow up here greatly.
