### ISSUE TITLE
X and Y not being honored?

### ISSUE THREAD

**Issue by joshuao3** [alafr/SVG-to-PDFKit#32]
Issue 1. If I add an SVG to a blank document with this line, the image is added halfway down the document:

SVGtoPDF(doc, svgdata, 0, 0);  

I would expect this image to be added to the top left of the document, and be sized to maximally cover the document without distorting.

Issue 2. If I add in width and height as options, I would expect that the SVG would be sized to to that exact size. However, I'm finding that this is not the case. In my case, I have an SVG that has the viewbox size in the file as "0 0 1360 744", so I as  the following:

    var doc_h = 6 * 72; // 6 inches
    var doc_w = 70 * 2.83465; // 70 mm
    var svg_w = doc_w; // same as document width
    var svg_h = 744 / 1360 * svg_w; // calculate svg height proportionately
    var doc = new PDFDocument({ size: [doc_w, doc_h], margin: 0, compress: false });
    SVGtoPDF(doc, contents, 0, 0, { width: svg_w, height: svg_h } ); 

The SVG would be expected to be in the top left of the document, the same width as the document. But alas, the SVG image is considerably smaller than the document. In order to make the image approximately the same width as the document I have to multiply doc_w by 1.3 to calculate svg_w. Am I misunderstanding something?

**Comment by alafr** [comment]
The x, y, width & height are the viewport's bounds and not the bounding box of the SVG content. The width & height by default are the page size. The SVG will be aligned inside the viewport depending of its preserveAspectRatio attribute. Try to inject the attribute `preserveAspectRatio="xMinYMin meet"` (top left alignment). It is quite complicated so I will add some documentation and/or change the options in SVG-to-PDFKit as soon as I have time to do it.

Issue 2 is because the PDF document uses pt units, and the SVG units are by default in px.
`1px = 72/96 pt` and `1pt = 96/72 px`. You have to multiply by 96/72 = 1.333333333333333

**Comment by joshuao3** [comment]
Thank you for the response! Here's what I ended up doing:
I ended up making preserveAspectRatio an additional parameter of the options structure that can be passed to the function. It ended up being about 6 lines of code changes and worked as expected. Problem solved. The reason I ended up doing it this way was so that the SVG would be predictably inserted into the PDF even if the SVG wasn't perfectly crafted. There are a lot of permutations within SVG files and a lot of "bad" files floating around.

Regarding the units... SVG are scalable, so in my mind the "unit" in an SVG is void of actual units. I think of them more as a ratio. I think the plugin would be better served by not executing this transformation from pixels to points. Thank you for the explanation.

**Comment by alafr** [comment]
I would be pleased if you made a pull request with the preserveAspectRatio option.

I will consider making optional the pixels to points scaling. While it's needed if the SVG uses units in cm or inches, it can be unwanted in many simple cases.

**Comment by joshuao3** [comment]
My first pull request ever. LOL. It'll take me a bit to climb up the learning curve so that I don't mess things up.

**Comment by joshuao3** [comment]
Pull request created. Thank you.

**Comment by alafr** [comment]
Pull request merged. Thank you very much!
