### ISSUE TITLE
svg  text can not support Chinese？

### ISSUE THREAD

**Issue by xinghunMeng** [alafr/SVG-to-PDFKit#35]
Thanks

**Comment by alafr** [comment]
That is very likely. I never used text in Chinese.
Which font and which text did you try?

**Comment by xinghunMeng** [comment]
@allfr, I check PDFkit own font do not support Chinese,  In pdfkit.js 13486 line havs all support font, I try all do not support Chiness

**Comment by alafr** [comment]
These are the standard PDF fonts and only support 216 characters.
You will have to find and download a font with Chinese support. There are lots of them available for free. Then, how to insert it depends if you use the browser or Node.
If Chinese text works in PDFKit and not in SVG-to-PDFKit I will try to fix it.

**Comment by alafr** [comment]
I did some tests and there is a bug in Fontkit (dependency of PDFKit): https://github.com/devongovett/fontkit/issues/92
I tried these chinese fonts and all three produce corrupted PDFs with missing letters (either with SVG-to-PDF or directly with PDFKit). It should work when/if the bug in Fontkit is fixed.
- http://www.freechinesefont.com/traditional-source-han-serif-tc-download/
- https://www.google.com/get/noto/#sans-hant
- http://www.freechinesefont.com/simplified-traditional-droid-sans-fallback/

**Comment by dapaer** [comment]
PDFKit has supported chinese. url: https://github.com/foliojs/pdfkit/issues/527

**Comment by alafr** [comment]
Chinese is not available in Standard PDF Fonts and there was an issue with embedded fonts. Which font did you use successfully in PDFKit so that i can debug SVG-to-PDFKit?
