### ISSUE TITLE
Unicode fonts

### ISSUE THREAD

**Issue by madcreep** [alafr/SVG-to-PDFKit#39]
Hi.
I'm getting an issue with importing unicode ttf fonts.

Here's my sails.js controller code:
`exportPDF: function(req, res) { 
    let svg = req.body.svg;
    svg = decodeURIComponent(Buffer.from(svg, 'base64'));
    const doc = new PDFDocument({compress: false, layout : 'landscape'});
    doc.registerFont('Trebuchet', 'font/trebuchet.ttf');
    doc.registerFont('Segoe', 'font/segoe.ttf');
    doc.pipe(res);
   svg2pdf(doc, svg, 0, 72, {widht: 1024, height: 600, fontCallback: function() {
	    return 'Trebuchet';
    }});
   doc.end();
}`

When I open the resulting PDF in Adobe Acrobat I get a message that the embedded font cannot be extracted (with some symbols before the font's name, like 'TFCUE+TrebuchetMS').
SVG I am trying to convert contains Cyrillic symbols, and they are not displayed.

![screen shot 2017-06-15 at 22 04 35](https://user-images.githubusercontent.com/2410787/27197397-b64e6440-5216-11e7-82c7-0019c9369389.png)

This code, though, works fine, and it is opened perfectly well:

`getPDF: function(req, res) {
    const doc = new PDFDocument({compress: false, layout : 'landscape'});
    doc.registerFont('Trebuchet MS', 'font/Trebuchet MS.ttf');
    doc.registerFont('Segoe UI', 'font/SegoeUIRegular.ttf');
    doc.pipe(res);
    doc.font('Trebuchet MS').text('Привет, Мир!');
    doc.end();
  }`

Here's a sample SVG:
[svg.svg.zip](https://github.com/alafr/SVG-to-PDFKit/files/1078714/svg.svg.zip)

**Comment by alafr** [comment]
I can't reproduce the issue with the attached sample. But it only has numbers and none cyrillic letter. Can you attach a sample with the Cyrillic text which produces the bug?

**Comment by madcreep** [comment]
Sorry, my fault.

Here it is.

[chart(6).svg.zip](https://github.com/alafr/SVG-to-PDFKit/files/1078881/chart.6.svg.zip)

**Comment by alafr** [comment]
I am still unable to reproduce, we probably don't have exactly the same version of the font:
[chart(6).pdf](https://github.com/alafr/SVG-to-PDFKit/files/1078929/chart.6.pdf)

Can you try to run this without SVG-to-PDFKit (directly in PDFKit)? It's the same text in the same order as in the SVG so it should produce the same embedded font. It could be a bug in PDFKit.
```
doc.font('Trebuchet MS')
   .text('Количество просмотров за период с 01.05.2017 по 31.05.2017 по типам медиа\nЖурнал \'РЭА\'\nГазета \'Энергичные люди\'\nНовости\nКалининская АЭС\nДепартамент информации\nЛенинградская АЭС\nСмоленская АЭС\nРостовская АЭС\nАЭС\nКурская АЭС\nБелоярская АЭС\nСтенгазета\n@РЭА\n@Энергичные люди\n0\n50\n100\n150\n200\n250\n300\n350\n400\n450\n500\n550\n600\nВсего')
```

**Comment by madcreep** [comment]
Sorry, seems there's nothing wrong with SVG-to-PDFKit. It seems the issue has something to do with the way I treat the source SVG: when I tried to convert a file from file system on server-side, I got a correct PDF.
