### ISSUE TITLE
Wrong marker arrowhead orientation (path curve)

### ISSUE THREAD

**Issue by diwe3** [alafr/SVG-to-PDFKit#43]
Hi,

if a path is a curve and an marker arrowhead is defined, then the arrowhead will always point to the right in the pdf. The "orient" attribute from the marker is set to "auto".
Straight paths are ok though.

[https://www2.pic-upload.de/img/33363319/svg_pdf_marker_arrowhead_comparison.png](url)

Thank you in advance.

**Comment by alafr** [comment]
Can you post the svg code so that I can try to find the bug?

**Comment by diwe3** [comment]
Weird that the rightmost arrow converts correctly but the one next to "time 3" does not.

`<svg id="svgcontent_0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="402" viewBox="0 0 1360 402" width="1360" overflow="hidden">
	<defs>
		<g id="arrow0">
			<path d="m-12,-3 9,3 -9,3 c 1,-2 1,-4 0,-6 z" class="s11"/>
			<path d="M0,0 -15,0" class="s12"/>
		</g>
		<marker id="arrowhead" style="fill: rgb(0, 65, 196);" markerHeight="7" markerWidth="10" markerUnits="strokeWidth" viewBox="0 -4 11 8" refX="15" refY="0" orient="auto">
			<path d="M0 -4 11 0 0 4z"/>
		</marker>
		<marker id="arrowtail" style="fill: rgb(0, 65, 196);" markerHeight="7" markerWidth="10" markerUnits="strokeWidth" viewBox="-11 -4 11 8" refX="-15" refY="0" orient="auto">
			<path d="M0 -4 -11 0 0 4z"/>
		</marker>
	</defs><g id="waves_0">
		<g id="lanes_0" transform="translate(60.5, 66.5)">
			<g id="wavearcs_0">
				<path id="gmark_c_d" d="M 246,75 c 56, 0 80, 30 80, 30" style="marker-end:url(#arrowhead);stroke:#0041c4;stroke-width:1;fill:none"/>
				<rect height="9" style="fill: rgb(255, 255, 255);" width="33" x="289.5" y="85"/>
				<text style="font-size: 10px;" text-anchor="middle" xml:space="preserve" x="306" y="93">
					<tspan>time 3</tspan>
				</text>
				<path id="gmark_d_e" d="M 326,105 c 0, 0 24, 30 80, 30" style="fill:none;stroke:#00F;stroke-width:1"/>
				<path id="gmark_e_f" d="M 406,135 c 56, 0 24, 0 80, 0" style="marker-end:url(#arrowhead);stroke:#0041c4;stroke-width:1;fill:none"/>
				<path id="gmark_f_g" d="M 486,135 566,105" style="marker-end:url(#arrowhead);stroke:#0041c4;stroke-width:1;fill:none"/>
				<path id="gmark_g_h" style="marker-end:url(#arrowhead);stroke:#0041c4;stroke-width:1;fill:none" d="M 566,105 c 56, 0 160, -30 100, 50"/>
			</g>
		</g>
	</g>
</svg>`

**Comment by alafr** [comment]
I should be fixed now. It was happening when the control point and end point of the curve were identical: it provokes a zero divided by zero problem. Interestingly, Chrome browser has the same buggy behaviour while Firefox and Internet Explorer render it correctly.

**Comment by diwe3** [comment]
Thank you for the fast fix. Works great.
