### ISSUE TITLE
Pattern with Path inside

### ISSUE THREAD

**Issue by ebremmer** [alafr/SVG-to-PDFKit#46]
Trying to use pattern with path inside:

`<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="612px" height="792px" viewBox="0 0 612 792" enable-background="new 0 0 612 792" xml:space="preserve">
<pattern  y="792" width="42" height="32" patternUnits="userSpaceOnUse" id="Volcano" viewBox="0 -32 42 32" overflow="visible">
	<g>
		<polygon fill="none" points="0,-32 42,-32 42,0 0,0 		"/>
		<path fill="#0034E3" d="M26,0c0-2.21,1.79-4,4-4c6.627,0,12-5.373,12-12s-5.373-12-12-12c-2.21,0-4-1.79-4-4h-2
			c0,3.314,2.686,6,6,6c5.523,0,10,4.477,10,10S35.523-6,30-6c-3.314,0-6,2.686-6,6H26z M16,0c0-2.21-1.79-4-4-4
			C5.373-4,0-9.373,0-16s5.373-12,12-12c2.21,0,4-1.79,4-4h2c0,3.314-2.686,6-6,6C6.477-26,2-21.523,2-16S6.477-6,12-6
			c3.314,0,6,2.686,6,6H16z"/>
	</g>
</pattern>
<rect x="51" y="50" fill="url(#Volcano)" stroke="#000000" stroke-miterlimit="10" width="146" height="159"/>
</svg>`

would you have suggestion what I might be doing wrong?

Seems this might be not supported. Using simple shapes (rect, circle) works just fine.

Actually, it seems the pattern is there but only MacOS finder renders it, anything else (like Preview, Chrome) shows blank space.
It comes out as expected in print.

**Comment by alafr** [comment]
Thanks for the bug report. It's not because of the path, it's a bug with the `viewBox` attribute. I tried to fix it. But i don't understand why the pattern was rendered in MacOs...

**Comment by ebremmer** [comment]
I think it's important to point out it renders in MacOS Finder thumbnail preview, while system viewer app 'Preview.app' does not. Would it be PDF version thing?

Where about the bug you think is ?

**Comment by alafr** [comment]
There was a bug in `SVG-to-PDFKit`: the 1st and 2nd numbers of the pattern's `viewBox` attribute weren't used at all. The `-32` in `viewBox="0 -32 42 32"` was completely ignored... => f817516

**Comment by ebremmer** [comment]
That did the trick, thank you.

There's one more problem when there's opacity within pattern but I can live without it.

Your library is live saver.

**Comment by alafr** [comment]
I added support for opacity in patterns in d978ab6

**Comment by ebremmer** [comment]
Thank you, You're a rockstar!
