### ISSUE TITLE
Firefox version PDF output differences

### ISSUE THREAD

**Issue by diwe3** [alafr/SVG-to-PDFKit#48]
Hi,

though the graphical output of a SVG in different Firefox versions is the same, the PDF output differs in support for basic features.

Firefox 34.0.5
- font-size has no effect
- font-weight has no effect (no bold)
- stroke-dasharray has no effect (no dashed line)
- stroke-width is always 1
- markers are not there
- dominant-baseline works (!)

Firefox 45.4.0
- markers are still not there
- dominant-baseline has no effect

Firefox 52.2.0
- dominant-baseline has no effect

I'd like to know why that is. Regarding these features they look the same on all those versions in the browsers, but not in the converted PDF file.
Unfortunately we cannot use the latest version of Firefox here and also no alternative browser.

Edit regarding dominant-baseline:
The reason for dominant-baseline is as follows:
I have a text element with 'dominant-baseline' on it and a tspan inside that should inherit it, which it does in FF34 (in browser and PDF).
Your this.get('dominant-baseline') function looks for that string which doesn't exist in FF34 in the css property of an element, but it does exist in FF52 -> css['dominant-baseline'] does not exist in FF34 but in FF52.
What does exist in both versions is css['dominantBaseline'], which is set to 'auto', but it is ignored. In FF52 the css['dominant-baseline'] exists and is also set on 'auto' and thus used, even though it should inherit from the parent element.

In other words, this works:
`<text x="0" y="0" text-anchor="middle" style="dominant-baseline: text-after-edge;">
    <tspan x="0" dy="0em" style="dominant-baseline: text-after-edge;">text</tspan>
</text>`

This does not:
`<text x="0" y="0" text-anchor="middle" style="dominant-baseline: text-after-edge;">
    <tspan x="0" dy="0em">text</tspan>
</text>`

Edit2 regarding markers:
Ok, I think I found the problem with the markers:
In FF45 the complete URL path to the editor.html is appended to the ID of the marker and therefore the regex in the "this.resolveURL" function doesn't filter as expected. I inserted `.*` before every `#` and `[^"']` in the first group that changed it to:
`/^\s*(?:url\(.*#(.*[^'"])\)|url\(".*#(.*)"\)|url\('.*#(.*)'\)|#(.*))\s*$/`
Now it works as expected and the markers appear in the PDF.

Regarding FF34: the css object doesn't have the properties marker-start, marker-mid and marker-end. I guess that's the problem there, but haven't tested it.

**Comment by alafr** [comment]
Does this happen with the `useCSS="true"` option? 
Can you try with `useCSS:"false"`?

**Comment by diwe3** [comment]
Ok, I tried using useCSS:"false" and use the css properties (markers, dominant-baseline, font-size, ...) as attributes in the svg elements on FF34. It seems to work, though I prefer to use internal CSS in the style element

**Comment by alafr** [comment]
I added support for style _attribute_ in v1.3.
This should now work:
```
<g style="stroke:red; dominant-baseline:middle">
  <text x="0" y="50">Test</text>
  <line x1="0" x2="50" y1="50" y2="50"/>
</g>
```
but not this:
```
<g>
  <style>text,line {stroke:red; dominant-baseline:middle;}</style>
  <text x="0" y="50">Test</text>
  <line x1="0" x2="50" y1="50" y2="50"/>
</g>
```
