### ISSUE TITLE
Adobe products complain about patterns

### ISSUE THREAD

**Issue by ebremmer** [alafr/SVG-to-PDFKit#49]
When I use patterns in my PDF's, Adobe Reader thinks file is broken or Adobe Illustrator says:

> Acrobat PDF File Format is having difficulties. Error while parsing a Form, Type 3 Font, or Pattern.

Since I have no forms nor fonts in there I think it must be pattern.

**Comment by auromota** [comment]
Same problem here. Adobe Acrobat Reader gives a warning and stops rendering the file when I use patterns in the SVG. If I remove the patterns, it works flawlessly.

**Comment by alafr** [comment]
Thanks for the report. There was some kind of infinite loop of patterns in the pdf file structure. Sorry for the long delay. Please reopen the issue if the problem persists.

**Comment by auromota** [comment]
@alafr I've tested it in Adobe Acrobat XI 11.0.09 and the problem is gone. However, when I open the same PDF in Adobe Acrobat Reader DC 2018.008.20044, it still fails, as the reader seems to still get into some infinite loop.

**Comment by alafr** [comment]
The problem comes probably from this line: https://github.com/alafr/SVG-to-PDFKit/blob/master/source.js#L17
Can you try to lower these values and see if the PDF is still failing?
If so I'll have to remove these arbitrary numbers.

**Comment by auromota** [comment]
@alafr Thanks for your answer and sorry for taking so long to reply. It was the problem indeed. The new version is working perfectly here. Thanks for sharing it with us! 👍
