### ISSUE TITLE
Is alignment-baseline not supported?

### ISSUE THREAD

**Issue by backsix** [alafr/SVG-to-PDFKit#56]
I'm trying to center text horizontally & vertically about the insertion point, but I'm finding that's not supported?

the following works within svg, but when applied to pdf the text isn't centered:

(i replaced the tags opening angle brackets with ... so it would display)

...svg viewBox="0 0 360 360">
...style>
.bN { text-anchor: middle;  alignment-baseline: central; }
.bP {fill-opacity: 0.4; stroke: #000;}
.../style>
...path d="M 120,120 L 240,120 L 240,240 L 120,240 z" class="bP" >
.../path>
...text x="180" y="180" style="font-size: 40px;" class="bN">
ABC
.../text>
.../svg

**Comment by alafr** [comment]
It's indeed not yet supported. The dominant-baseline is supported instead (it has a very similar effect but it's not exactly the same) . I will try to add support for alignment-baseline soon.
The <style> element is not supported too

**Comment by backsix** [comment]
I appreciate your response and your terrific project.
I'll investigate dominant-baseline, thanks.
leveraging the browsers interpretation of the style tag at least with chrome is working perfectly for me, so although <style> tags aren't supported directly, I'm getting great results indirectly.

**Comment by alafr** [comment]
I added support for the `alignment-baseline` attribute.
However `dominant-baseline` is usually better because it's also supported by Firefox and it's value is inherited by `tspan`s & and other children of the `text` element
