### ISSUE TITLE
Adding multiple SVGs with clip-path, duplicates the last one

### ISSUE THREAD

**Issue by sajjad-shirazy** [alafr/SVG-to-PDFKit#70]
Hi,

 take a look:
https://runkit.com/sajjad-shirazy/5a796f6ba3b90a001274c4fb
 the first svg contains a blue circle but it shows it red. could you please help me how i can solve this bug.
the lib duplicates the element of the last svg to the first one ! 

thanks

**Comment by alafr** [comment]
Thanks for the report. The clip path of the 1st svg was being overwriten when other svgs are inserted in the same pdf page.

**Comment by sajjad-shirazy** [comment]
Thanks @alafr for the quick fix
