### ISSUE TITLE
Issue with base64 encoded image in svg

### ISSUE THREAD

**Issue by joakimlustig** [alafr/SVG-to-PDFKit#71]
Thanks for making svg-to-pdfkit! This might sound weird, but this is how I use the library. I export a canvas to svg using the library 'canvas2svg'. Then I export that svg to pdfkit using 'svg-to-pdfkit'. The reason is that I haven't found any other way to get high quality images and text from canvas to pdf.

In my canvas I combine text with imported images, which works great for most cases I have tried. But I have one image that generates quite strange pdf output, altough the svg exported from the canvas looks good. So there is probably some part of this svg that messes things up for svg-to-pdfkit or for pdfkit, but I can't figure out what.

This is the svg I'm importing to svg-to-pdfkit: https://www.dropbox.com/s/vr02r6lif2flw9k/test.svg?dl=0

This is the pdf output I get: https://www.dropbox.com/s/sy5fy82r1e27xca/test.pdf?dl=0

Any idea of why this is happening?

Thank you!

**Comment by alafr** [comment]
I only received the pdf file. Can you attach the svg file?

**Comment by joakimlustig** [comment]
Sorry I messed up the links. I edited my post with the right one now.

**Comment by alafr** [comment]
It's a bug in PDFKit: [pdfkit/issues/339](https://github.com/devongovett/pdfkit/issues/339),  [pdfkit/issues/766](https://github.com/devongovett/pdfkit/issues/766)

**Comment by joakimlustig** [comment]
Oh I see! Thanks a lot! I posted a way to recreate the issue in [pdfkit/issues/766](https://github.com/devongovett/pdfkit/issues/766).
