### ISSUE TITLE
BUG UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by x3r10n** [alafr/SVG-to-PDFKit#74]
I get a : svg.getElementsByTagName is not a function when calling the svg-to-pdf constructor.

Any idea why?

**Comment by x3r10n** [comment]
found how to fix it in my code but still dont know why it wasn't working. 
I change :
` svgToPDF(doc, Buffer.form(svgString), 0, 0);`
to 
` svgToPDF(doc, svgString, 0, 0);`

**Comment by alafr** [comment]
SVGtoPDF doesn't accept buffers, only strings or SVGElement in the browser
