### ISSUE TITLE
Main clip group does not observe assumePt

### ISSUE THREAD

**Issue by akaleeroy** [alafr/SVG-to-PDFKit#76]
![image](https://user-images.githubusercontent.com/4068718/38804397-ed30af3c-417a-11e8-858f-0db614c31deb.png)

I'm creating a PDF with `assumePt: true`. The artboard is correctly sized but the main clip group still uses what looks like original `getBoundingBox` values, not converted with `pxToPt`.

:package: [Sample PDF and ZIP](https://github.com/alafr/SVG-to-PDFKit/files/1943587/test.zip)

**Comment by alafr** [comment]
Can you send the SVG file?

**Comment by akaleeroy** [comment]
:package: [Sample PDF and ZIP](https://github.com/alafr/SVG-to-PDFKit/files/1943587/test.zip)

**Comment by akaleeroy** [comment]
If I don't set `assumePt: true` the artwork is scaled wrong (`72mm × 41.25mm` instead of `96mm × 55mm`)

![image](https://user-images.githubusercontent.com/4068718/39238561-395b4de6-4887-11e8-9e89-4579eba7eea9.png)

Should I do something else to scale everything correctly together to the size I meant?

**Comment by akaleeroy** [comment]
Not an SVG-to-PDFKit bug. 

SVG spec sizes millimeters at 96dpi (CSS units) but my chart library was not.
