### ISSUE TITLE
Errors while attempting to convert local svg file

### ISSUE THREAD

**Issue by smehtaca** [alafr/SVG-to-PDFKit#81]
**Description:**

SVGtoPDF(nodejs) runs into an error when trying to convert a svg file. This occurs with any svg file(valid or invalid).

Here is the code I am using to read a svg file and convert to string:
```
fs.readFile(svg, function(err, data) {
  if (err) throw err;
  svg = data.toString();
  SVGtoPDF(doc, svg, 0, 0);
}); 
```

Here is the error produced: 

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PDFReference.Writable.write (_stream_writable.js:291:5)
    at PDFPage.write (/Users/smehta/code/pdfkit-test/node_modules/pdfkit/js/page.js:95:27)
    at PDFDocument.addContent (/Users/smehta/code/pdfkit-test/node_modules/pdfkit/js/document.js:161:17)
    at PDFDocument.save (/Users/smehta/code/pdfkit-test/node_modules/pdfkit/js/mixins/vector.js:19:19)
    at SVGtoPDF (/Users/smehta/code/pdfkit-test/node_modules/svg-to-pdfkit/source.js:2472:13)
    at /Users/smehta/code/pdfkit-test/pdfkit.js:29:3
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PDFReference.Writable.write (_stream_writable.js:291:5)
    [... lines matching original stack trace ...]
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

If I'm attempting to convert all the svg files in a directory, the error generated sometimes is the following:
```
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
```

I've validated all the svg files I'm using with [validator.nu
](https://www.validator.nu)

**How to replicate:**
Use fs.readFile to read a svg file and convert to string using `toString()`

**Comment by alafr** [comment]
The first error appears to happen outside of SVG-to-PDFKit. Does the error happens if you replace `SVGtoPDF(doc, svg, 0, 0)` with `doc.text('test', 0, 0)` at the same spot in your code?

To investigate the last error I would need the concerned svg, it might have a syntax unsupported by SVG-to-PDFKit

**Comment by smehtaca** [comment]
First appears with doc.text, probably has something to do with my code. The svgs are attached for the second error. I've only validated the first one but even reading only that file, the same error occurs.
[svgs.zip](https://github.com/alafr/SVG-to-PDFKit/files/2189783/svgs.zip)

**Comment by alafr** [comment]
Those SVG are converted correctly if SVG-to-PDFKit is used in the browser. 
So it probably has to do with Node's filesystem functions. You could try the following:

- replace `readFile(svg, callback)` with `readFileSync(svg)` (to check if it's a asynchronous code issue)
- add to the `readFile` call the encoding `utf-8` option (the svg has the following special characters: `“”`)
- escape those special characters or eventually remove them for debugging purposes
- init the PDFDocument just before SVGtoPDF (various things could happen to the document while waiting for the svg file to be read)

**Comment by smehtaca** [comment]
Using readFileSync fixed the issue, thanks a lot! Closing this issue.

**Comment by LeiX-21** [comment]
I have the same problem with this script , i got error SVGtoPDF: the input does not look like a valid SVG
[index.zip](https://github.com/alafr/SVG-to-PDFKit/files/12600033/index.zip)
and I dont know how to fix the code, any help?
