### ISSUE TITLE
bundled pdfkit

### ISSUE THREAD

**Issue by awerlang** [alafr/SVG-to-PDFKit#83]
Hey, how did you produce the `pdfkit.js` that's in the `examples` folder? Because building pdfkit myself I get a file of about 1,9MB (10% smaller). And it exhibits a different behavior on browser, calling `nextTick()` a lot, and also another weird conflict with Angular/zone.js.

I believe is a dependency with a newer version on my environment, but I'm unsure what is is. If you could share your `package-lock.json` file (if you have one) that would be useful.

Thanks!

**Comment by alafr** [comment]
Here is how I build it: https://github.com/devongovett/pdfkit/wiki/How-to-compile-PDFKit-for-use-in-the-browser

**Comment by awerlang** [comment]
Thanks a bunch! I was building from the repo itself, which uses an older version of browserify as per package.json. But with these instructions it's working flawless. Thanks again!
