### ISSUE TITLE
ES6 keywords in source.js

### ISSUE THREAD

**Issue by tomecko** [alafr/SVG-to-PDFKit#88]
Would you consider releasing `ES5` version of `source.js` without such keywords as `const` or `let`?

There is a possibility to publish a library for both targets, ES5 and ES6. You may see https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for

Using `var` instead may be a quick workaround.

**Comment by alafr** [comment]
I think this will be a wontfix, because svg-to-pdfkit can't be used without PDFKit, and PDFKit releases also contains these keywords.
