### ISSUE TITLE
Can't render a particular PNG image

### ISSUE THREAD

**Issue by chadkirby** [alafr/SVG-to-PDFKit#93]
Hi, I ran into a particular PNG image that doesn't render properly when I create a PDF. I attached the svg in question as a text file, as well as a pdf with a rendering of the image that I'd expect and a pdf with a rendering of the image that I get.

I haven't debugged too far into this issue yet. Other PNG images render fine. I'm not sure what's wrong with this particular image.

[actual.pdf](https://github.com/alafr/SVG-to-PDFKit/files/2823859/actual.pdf)
[expected.pdf](https://github.com/alafr/SVG-to-PDFKit/files/2823860/expected.pdf)
[7.txt](https://github.com/alafr/SVG-to-PDFKit/files/2823847/7.txt)

**Comment by alafr** [comment]
This was an issue with older pdfkit versions. Can you try to update pdfkit?

**Comment by chadkirby** [comment]
I'm using 0.9.0, which looks to be the most up to date. This problem is definitely with pdfkit--it'll reproduce in plain-vanilla PDFKit. If I extract the PNG from the svg, save it as a new file using an image editor, reconvert it to base64, and insert that into a PDF, then it will render fine. So, there's something funny about this image.
