### ISSUE TITLE
Error with rendering pdf : TypeError: svg.getElementsByTagName is not a function

### ISSUE THREAD

**Issue by dingchao-95** [alafr/SVG-to-PDFKit#95]
I received this error when i tried to pass it through the prototype function. No idea why its giving me the error. Code as shown below : 
   doc.addPage({size:'LEGAL',layout: 'landscape'})
        .font('Times-Roman',35)
        .text('Chart analysis',{
            width: 300,
            align: 'left'
        })
        .addSVG(drawChart.returnChart(req.body.choiceArr) , 100,150, {
            fit: [1500,500],
            align: 'left',
            useCSS: true
        });

**Comment by dingchao-95** [comment]
I solved the issue. It seems that svgtopdf doesnt take in an async value(buffer). So i had to use promises within the function.

**Comment by alex88** [comment]
@dingchao-95 can you show an example? I've the same issue with nodejs but I pass the actual svg string

**Comment by dingchao-95** [comment]
@alex88 for my case, i was trying to do a POST call through NodeJS to render pdf onto the client side. Because i had 2 different charts to display within the PDF itself, I had to do something like 
![image](https://user-images.githubusercontent.com/36474437/54883643-b9c6e900-4ea2-11e9-9da6-3040cfc4ca84.png)

and pass it into the addSVG function like so : 
![image](https://user-images.githubusercontent.com/36474437/54883649-dbc06b80-4ea2-11e9-9f01-50ff2ae4334d.png)

Hope it helped.

**Comment by alex88** [comment]
Thanks, yeah I've found out that my problem was that I was passing a buffer from readFile instead of the string 😄 thanks for the quick response!
