### ISSUE TITLE
Bug: Curve path contains scientific notation causing pdf rendering to be incorrect

### ISSUE THREAD

**Issue by ClockGet** [alafr/SVG-to-PDFKit#98]
I think I find a bug like [#73](https://github.com/alafr/SVG-to-PDFKit/issues/73). I has a svg and when I open the exported pdf by Adobe Reader in windows 10, it looks like the curve path is incorrect.
And I deep through the source code, found that in the function [SvgShape.A](https://github.com/alafr/SVG-to-PDFKit/blob/master/source.js#L850), after a series of mathematical changes, the data may become a very small number represented by scientific notation(like 1.23456e-18). Then the pdf may be incorrectly rendered or there is a blank page. I use Preflight tool in Adobe Acrobat to detect the syntax issues, and it reports a number in scientific notation cannot be parse. So I edit the addCommand function like:
```
this.addCommand = function (data) {
            //fix scientific notation & decimal places
            for (var i = 3; i < data.length; i++) {
                if (!isNaN(data[i]) && isFinite(data[i]) && (parseInt(data[i]) !== parseFloat(data[i]))) {
                    data[i] = Math.round(data[i] * 1000) / 1000;
                }
            }
            ......
```
Then the pdf is rendered correctly. This modification is very effective for me, I don't know if I can send you a pull request?

**Comment by alafr** [comment]
Which PDFKit version do you use? PDFKit since v0.8.3 rounds small numbers to avoid this issue...

**Comment by ClockGet** [comment]
I downloaded a prebuilt version of PDFKit from Github, it is marked as the Latest release, I did not check carefully its version, I made a mistake. I just downloaded the version 0.9.0 and test again, PDFkit has indeed avoided this problem, thank you very much!
